# NumPy는 Python extension으로 산술 연산 및 matrix 연산에 유용

In [1]:
# 파이썬은 mathematical operations 부족, speed가 늦음
height = [170, 180, 170]
weight = [60, 70, 65]
weight/height # 이런 연산이 안 된다. 이 때 solution이 NumPy

TypeError: unsupported operand type(s) for /: 'list' and 'list'

NumPy
1. Numeric Python
2. Alternative to Python List : NumPy Array
3. Calculations over entire arrays
4. Easy and fast

In [2]:
import numpy as np # 꼭 이렇게 import문 작성해야함
np_height = np.array(height)
np_weight = np.array(weight)
np_weight / np_height

array([0.35294118, 0.38888889, 0.38235294])

In [3]:
# ndarray = N-dimensional array
print(type(np_weight))

<class 'numpy.ndarray'>


In [4]:
# NumPy array creation
# explicity from a list of values
np.array([1, 3, 4, 5])

array([1, 3, 4, 5])

In [5]:
data = [[1,2], [11, 22], [111, 222]] # matrix는 list of list로 만든다.
a = np.array(data)
print(a)
print(type(a))

[[  1   2]
 [ 11  22]
 [111 222]]
<class 'numpy.ndarray'>


In [6]:
# as a range of values
np.arange(10) # 0부터 9까지인 벡터가 만들어진다.

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
# by specifying the number of elements
# 0에서부터 1까지 5등분
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [8]:
# NumPy arrays contain only one type
# 넘파이는 type을 하나만 갖게 된다.
a = np.array([1.0, "is", True])
print(a) # 전부 String으로 바꿔서 계산이 된다.

['1.0' 'is' 'True']


In [9]:
# Different use of + in Python and NumPy
# 파이썬과 넘파이에서 +의 사용이 약간 다르다.
python_list = [1,2,3]
np_list = np.array([1,2,3])
print(python_list + python_list)
print(np_list + np_list)

[1, 2, 3, 1, 2, 3]
[2 4 6]


In [10]:
# NumPy Subsetting
bmi = np.array([10, 30, 50, 70])
print(bmi[2])
print(bmi > 35) # 35보다 큰 index는 True가 된다.
print(bmi[bmi>35]) # True인 index만 출력된다. boolean indexing

50
[False False  True  True]
[50 70]


In [11]:
an_array = np.array([ [1,2,3,4,5], [11,12,13,14,15] ])
print(an_array)
print(an_array[0])
print(an_array[0][2])
print(an_array[0, 2]) # 위에 있는 표현과 같은 말
print(an_array[:, 1:3]) # 첫 번째 index는 row, 두 번째 index는 column

[[ 1  2  3  4  5]
 [11 12 13 14 15]]
[1 2 3 4 5]
3
3
[[ 2  3]
 [12 13]]


NumPy Utilities
1. create a 2X2 array of zeros
2. create a 2X2 array filled with 9.0
3. create a 2X2 matrix with the diagonal 1s and the others 0
4. create an array of ones
5. create an array of random floats between 0 and 1

In [12]:
print(np.zeros((2,2))) # 괄호 2개 주의, argument가 tuple이니까
print(np.full((2,2), 9.0))
print(np.eye(2,2)) # 대각선이 1로 채워짐
print(np.ones((2,2)))
print(np.random.random((2,2))) # 0과 1 사이의 random number 생성

[[0. 0.]
 [0. 0.]]
[[9. 9.]
 [9. 9.]]
[[1. 0.]
 [0. 1.]]
[[1. 1.]
 [1. 1.]]
[[0.52935727 0.07582026]
 [0.28111714 0.2733965 ]]


In [13]:
# NumPy slicing
an_array = np.array([[11,12,13,14], [21,22,23,24], [31,32,33,34]])
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [14]:
a_slice = an_array[:2, 1:3]
print(a_slice)

[[12 13]
 [22 23]]


Use arange and reshape to create an array in advance

In [15]:
a = np.arange(15) # 0부터 14까지인 벡터가 만들어진다.
print(a)
b = a.reshape(3,5) # a를 3X5 matrix로 바꾸겠다.
print(b)
print(b[:2, 2:3])
print(a[0:5:2])
print(a[::2]) # 출력 주의

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[2]
 [7]]
[0 2 4]
[ 0  2  4  6  8 10 12 14]


In [16]:
print("Before : ", an_array[0,1]) # inspect the element at 0,1
a_slice[0,0] = 1000 # a_slice[0,0] is the same piece of data as an_array[0,1]
print("After : ", an_array[0,1])

Before :  12
After :  1000
