Slice 된 것이 vector인지 matrix인지 구분할 필요가 있음

In [1]:
import numpy as np
an_array = np.array([[11,12,13,14], [21,22,23,24], [31,32,33,34]])
print(an_array)
row_rank1 = an_array[1, :]
print()
print(row_rank1, row_rank1.shape) # [] and vector

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]

[21 22 23 24] (4,)


In [2]:
row_rank2 = an_array[1:2, :]
print(row_rank2, row_rank2.shape) # [[]] and matrix

[[21 22 23 24]] (1, 4)


In [3]:
col_rank1 = an_array[:, 1]
col_rank2 = an_array[:, 1:2]
print(col_rank1, col_rank1.shape) # output이 vector
print(col_rank2, col_rank2.shape) # output이 matrix

[12 22 32] (3,)
[[12]
 [22]
 [32]] (3, 1)


In [4]:
an_array = np.array([[11,12,13,14], [21,22,23,24], [31,32,33,34], [41,42,43,44]])
print('Original Array:\n', an_array)
print(an_array.shape)

Original Array:
 [[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]
 [41 42 43 44]]
(4, 4)


In [5]:
row_indices = np.arange(4) # arange로 0부터 3까지인 벡터를 만든다.
col_indices = np.array([0,1,2,0])
print(row_indices)
print(col_indices)
print(zip(row_indices, col_indices)) # zip function 사용해서 각각의 element 가지고 tuple 만들기

[0 1 2 3]
[0 1 2 0]


In [6]:
for row, col in zip(row_indices, col_indices):
    print(row, " ", col)

0   0
1   1
2   2
3   0


In [7]:
print("Values : \n", an_array[row_indices, col_indices])
# zip한 형태로 index를 찾고, element 꺼내오고, 벡터 형태로 리턴 

Values : 
 [11 22 33 41]


Boolean array를 이용한 numpy array indexing

In [8]:
an_array = np.array([[11,12], [21,22], [31,32]])
filter = (an_array > 15) # 각각의 element를 15와 비교
print(an_array)
print()
print(filter)

[[11 12]
 [21 22]
 [31 32]]

[[False False]
 [ True  True]
 [ True  True]]


In [9]:
print(an_array[filter]) # True인 element를 찾아서 벡터 형태로

[21 22 31 32]


In [10]:
an_array[an_array > 15] # 이것도 역시 벡터로

array([21, 22, 31, 32])

In [11]:
an_array[(an_array > 20) & (an_array < 30)]

array([21, 22])

In [12]:
print(an_array[an_array % 2 == 0])
an_array[an_array % 2 == 0] += 100
print(an_array)

[12 22 32]
[[ 11 112]
 [ 21 122]
 [ 31 132]]


In [13]:
a = np.arange(15).reshape((3,5))
print(a)
print()
b = (a % 3 == 0)
print(b)
a[b]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

[[ True False False  True False]
 [False  True False False  True]
 [False False  True False False]]


array([ 0,  3,  6,  9, 12])

Datatype을 지정할 수도 있다.

In [14]:
ex1 = np.array([11, 12])
ex2 = np.array([11.0, 12.0])
ex3 = np.array([11, 12], dtype=np.int64)
print(ex1.dtype)
print(ex2.dtype)
print(ex3.dtype)

int32
float64
int64


In [15]:
ex4 = np.array([11.1, 12.7], dtype=np.int64)
print(ex4)
print(ex4.dtype)
ex5 = np.array([11, 12], dtype=np.float64)
print(ex5)
print(ex5.dtype)

[11 12]
int64
[11. 12.]
float64


Arithmetic array operation

In [16]:
x = np.array([[111, 112], [121, 122]], dtype = np.int)
y = np.array([[211.1, 212.1], [221.1, 222.2]], dtype = np.float64)
print(x+y)
print(np.add(x,y))

[[322.1 324.1]
 [342.1 344.2]]
[[322.1 324.1]
 [342.1 344.2]]


In [17]:
print(x-y)
print(np.subtract(x,y))

[[-100.1 -100.1]
 [-100.1 -100.2]]
[[-100.1 -100.1]
 [-100.1 -100.2]]


In [18]:
print(x/y)
print(np.divide(x,y))

[[0.52581715 0.52805281]
 [0.54726368 0.54905491]]
[[0.52581715 0.52805281]
 [0.54726368 0.54905491]]


In [19]:
print(np.sqrt(x))
print(np.exp(x))

[[10.53565375 10.58300524]
 [11.         11.04536102]]
[[1.60948707e+48 4.37503945e+48]
 [3.54513118e+52 9.63666567e+52]]


Reshaping

In [20]:
a = np.array(range(8))
print(a)
print(a.shape) # vector

b = a.reshape((a.shape[0],1))
print(b)
print(b.shape)

c = a.reshape(2,4) # 2X4로 reshape
print(c)

d = a.reshape(2, 2, 2) # 2X2가 2개 있는 상태
print(d)

[0 1 2 3 4 5 6 7]
(8,)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]
(8, 1)
[[0 1 2 3]
 [4 5 6 7]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


"-1" 활용하면 넘파이가 알아서 shape을 결정, "-1"은 한 번만 사용 가능

In [21]:
b = np.arange(12).reshape(2,6)
print(b)

c = b.reshape(3,4)
print(c)

d = b.reshape(3,-1)
print(d)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


Random number generation (randn, rand, normal 사용)

In [22]:
# 평균 0, 표준편차 1인 임의의 random 2X5 matrix
arr = np.random.randn(2,5) # randn : matrix가 나오게 함
print(arr)

# 0과 1 사이의 random number matrix
arr = np.random.rand(2,5)
print(arr)

# normal은 평균과 표준편차를 지정할 수 있음, vector 나옴
# 평균 50, 표준편차 0.1, 개수 5개
arr = np.random.normal(50, .1, 5)
print(arr)

[[-1.12221344 -1.51776871 -0.40597655  0.90457778  0.09421687]
 [ 0.03634111 -0.71301226  0.770092   -0.0609522   0.19583798]]
[[0.39400113 0.09706802 0.23275451 0.50765559 0.41600698]
 [0.92866338 0.15201117 0.2977618  0.56947122 0.89475323]]
[49.98773293 50.17609496 49.99789955 49.93980824 49.85726099]
